### ISSUE TITLE
[Endpoints] Games

### ISSUE THREAD

**Issue by bartoj35** [SoptikHa2/shifra#35]
**Path:** ```/api/games```
**Type:** GET 
**Requirements:** returns all ciphergames visible to public

**Comment by bartoj35** [comment]
Endpoint placed in ciphergamesFuncs

**Comment by SoptikHa2** [comment]
Mohli bychom možná ještě rozšířit to původní zadání a dodat tam, že hru vidí kromě časového kritéria i uživatelé co jsou `root` nebo admini dané hry?

**Comment by bartoj35** [comment]
@SoptikHa2 malo by to tam byt, v pull requeste potom poprosim sanity check na ten select <3
