### ISSUE TITLE
[ Chyba návrhu ] Připojení k více než 1 teamu je možné

### ISSUE THREAD

**Issue by MistrMxyzptlk** [SoptikHa2/shifra#98]
- 1 team se může zapojit ve více šifrovačkám
- 1 uživatel se může přidat do 1 nebo více teamů

V případě, že toto je možné je možné, aby se uživatel zapojil vícekrát do stejné šifrovačky a co víc.

Možná řešení:

1. V případě připojení do další šifrovačky, uživatele vyhodit z té původní (stráta historie -> přidat tabulku s historií teamu??? )
2. Team <-> cipher game, převést z M:N na 1:N (v případě znovu použítí teamu, přidat ještě jeden záznam automaticky, tak aby se nestratil záznam o starém teamu)

**Comment by SoptikHa2** [comment]
Vyřešil bych, až marek mergne svoje změny, ať toho neměníme tolik naráz.

Každopádně to je problém, který určitě musíme vyřešit. Struktura DB as of now:
![shifra-dev](https://user-images.githubusercontent.com/24734779/131206003-aa6cba5e-fb94-45ea-b807-66855472d8ed.png)

Moc nevidím, jak to ošetřit návrhem databáze. (Also, asi chceme taky vypnout možnost, aby jeden tým byl ve více šifrovačkách? Z hlediska uživatele by ani neměla být možnost, jak se k tomu dostat, tak to rovnou můžeme potlačit v databázi).

Takže to možná bude stačit naifovat v databázi. Aby člověk nemohl založit/připojit se k teamu, pokud už se dané šifrovačky účastní.

To, že uživatel může posbírat hinty, leavnout team, a znova se připojit a řešit to instantně bez hintů, asi budeme ignorovat - stejně si člověk může založit fake účet, tak to asi nemá cenu řešit.

**Comment by SoptikHa2** [comment]
A přemýšlím nad vymazáním celé tabulky cipher_game_team, a prostě evidovat ID šifrovačky pro daný team, takže team může patřit jen k jedné šifrovačce. Dává mi to větší smysl.

**Comment by severma2** [comment]
Tak vytvoření týmu je vždy jen při připojení k dané šifrovačce ne? Tam by ani neměla být možnost použít stejný tým jinde. Maximálně tak stejným jménem a stejnými členy, ale nebude to ten samý tým

**Comment by SoptikHa2** [comment]
Fixed by #126

**Comment by MistrMxyzptlk** [comment]
@SoptikHa2 shouldn't this be closed?
